// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEHb3Umy7YNEuUrtiW-9iNTZOu5fB_T24',
    appId: '1:363355444622:web:c783ba66e6460b216140df',
    messagingSenderId: '363355444622',
    projectId: 'bookmyslot-50bd9',
    authDomain: 'bookmyslot-50bd9.firebaseapp.com',
    storageBucket: 'bookmyslot-50bd9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbTxn27XLnfcT9N2-YjSDXkJpdo-deDWE',
    appId: '1:363355444622:android:1396f4ab3e0001136140df',
    messagingSenderId: '363355444622',
    projectId: 'bookmyslot-50bd9',
    storageBucket: 'bookmyslot-50bd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAE-ZC91HBX-P2MiZhRT87-QTOAvMQTCg',
    appId: '1:363355444622:ios:58aa14f3d206afe46140df',
    messagingSenderId: '363355444622',
    projectId: 'bookmyslot-50bd9',
    storageBucket: 'bookmyslot-50bd9.firebasestorage.app',
    iosBundleId: 'com.example.bt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAE-ZC91HBX-P2MiZhRT87-QTOAvMQTCg',
    appId: '1:363355444622:ios:58aa14f3d206afe46140df',
    messagingSenderId: '363355444622',
    projectId: 'bookmyslot-50bd9',
    storageBucket: 'bookmyslot-50bd9.firebasestorage.app',
    iosBundleId: 'com.example.bt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEHb3Umy7YNEuUrtiW-9iNTZOu5fB_T24',
    appId: '1:363355444622:web:b42979d675fd57306140df',
    messagingSenderId: '363355444622',
    projectId: 'bookmyslot-50bd9',
    authDomain: 'bookmyslot-50bd9.firebaseapp.com',
    storageBucket: 'bookmyslot-50bd9.firebasestorage.app',
  );
}
